server:
  port: 9201

logging:
  level:
    com.tommy: DEBUG
    org.springframework.orm: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: 0000
    driverClassName: org.h2.Driver # tobe mysql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # tobe validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
