name: Checks and Coverage Report
on:
  pull_request:
  workflow_dispatch:

env:
  GRADLE_BUILD_CMD: 'check --parallel'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ env.GRADLE_BUILD_CMD }}

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

      - name: Test Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: Test Coverage Report
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
